<?php
    return [
        // 'vendor_reports_dir'=>'uploads/vendor_report',
        // 'ad_banner_dir'=>'uploads/banner',
        // 'category_dir'=>'uploads/category',
        // 'subcategory_dir'=>'uploads/subcategory',
        // 'vendor_dir'=>'uploads/vendor',
        // 'hotel_dir'=>'uploads/hotel',
        // 'menu_dir'=>'uploads/menu',
        // 'super_vendor_dir'=>'uploads/super_vendor',
        // 'voucher_dir'=>'uploads/voucher',
        // 'voucher_attribute_dir'=>'uploads/voucher/attribute',
        // 'deal_dir'=>'uploads/deal',
        // 'deal_barcode_dir'=>'uploads/deal/barcode',
        // 'deal_attribute_dir'=>'uploads/deal/attribute',
        // 'product_dir'=>'uploads/product',
        // 'order_dir'=>'uploads/order',
        // 'customer_dir'=>'uploads/customer',
        // 'drivers_dir'=>'uploads/drivers',
        // 'deal_to_customer_pdf_dir'=>'uploads/deal_to_customer_pdf',
        // 'one_delivery_area_dir'=>'uploads/one_delivery_area',
        // 'inventory_product_dir'=>'uploads/inventory_product',
        // 'gift_card_style_dir'=>'uploads/gift_card_style',
        // 'service_dir'=>'uploads/service',
        // 'service_facility_dir'=>'uploads/service_facility',

        'back'=>'back',
        'admin'=>'admin',
        'front'=>'front',
        'back_asset'=>'assets/back',
        'front_asset'=>'assets/front',

        // 'FCM_KEY' => 'AAAAk_6IfDs:APA91bEIHBMTPeB86ZOxFaCPZtdZ9QWU4st2ORlqThQZYvcmlkeH_3kKQM0Mgyn7J_BKwIxxuEOYMuXbgBC68Iy3wkt5204UVGKeamri1n4g_CmPm30_xrMrsFZepkZ_-kIfTQ-FiSxk',
        // 'GOOGLE_MAP_KEY' => 'AIzaSyAYBKeS1GJRYpeNPoP88Pfk_GFq3VmaIug',
        // 'GOOGLE_MAP_BASE' => 'https://maps.googleapis.com/maps/api',
        // 'GUZZLE_SSL' => false,
    ];
